### ISSUE TITLE
Metodologia - Etiquetas

### ISSUE THREAD

**Issue by MatheusVinicio** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t7-controle-de-horas-de-treinamento#14]
Tipo de filtro realizado para categorizar as atividades.

**Comment by Daniellasancosta** [comment]
Descrever os filtros utilizados e inserir no documento base

**Comment by LeonardoZanette** [comment]
Bug (Erro no código)
Desenvolvimento (Development)
Documentação (Documentation)
Gerência de Projetos (Project Management)
Infraestrutura (Infrastructure)
Testes (Tests)

<html>
<body>


Rótulo | Descrição
-- | --
bug | Indica um problema inesperado ou um comportamento não intencional
documentation | Indica a necessidade de aprimoramentos ou adições à documentação
duplicate | Indica problemas, solicitações de pull ou discussões semelhantes
enhancement | Indica novas solicitações de recurso
good first issue | Indica um bom problema para contribuidores principiantes
help wanted | Indica que um mantenedor deseja ajudar em um problema ou uma pull request
invalid | Indica que um problema, uma solicitação de pull ou uma discussão não é mais relevante
question | Indica que um problema, uma solicitação de pull ou uma discussão precisa de mais informações
wontfix | Indica que o trabalho não continuará em um problema, solicitação de pull ou discussão

<br class="Apple-interchange-newline">
</body>
</html>
